run:
  timeout: 2m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosimple
    - typecheck
    - revive

issues:
  exclude-use-default: false
